CREATE TABLE contacts (
  CONTACT_ID INTEGER IDENTITY PRIMARY KEY
);

CREATE TABLE applications (
  APPLICATION_ID INTEGER IDENTITY PRIMARY KEY,
  DT_CREATED DATE,
  PRODUCT_NAME VARCHAR(255),
  CONTACT_ID INTEGER,
  FOREIGN KEY (CONTACT_ID) REFERENCES contacts(CONTACT_ID)
);